##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  项目启动端口  ###################
server:
  port: 80

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
      
weixin: 
  token: weixin
  encoding-type: aes
  encoding-aes-key: oK6kttokB4HQ4HiKSjKqvAGIJplWWQSXzYRCZxeGpBR
  appid: wx5c13a8f3b5f12b01

logging:
  level.root: DEBUG
  path: logs/
  file: weixin.log
